# Generated by Django 4.1.4 on 2022-12-20 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                ("description", models.TextField(max_length=500, verbose_name="説明")),
                (
                    "thumbnail",
                    models.ImageField(upload_to="thumbnail/", verbose_name="サムネイル"),
                ),
                (
                    "uploaded_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="動画投稿時刻"),
                ),
                ("filename", models.CharField(max_length=200, verbose_name="ファイル名")),
                ("views_count", models.IntegerField(default=0, verbose_name="視聴回数")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserVideoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "play_speed",
                    models.CharField(
                        choices=[("slow", "スロー"), ("standard", "標準"), ("double", "倍速")],
                        default="standard",
                        max_length=20,
                        verbose_name="再生速度",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
