# Generated by Django 4.1.4 on 2022-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, verbose_name="ユーザ名"),
        ),
    ]
