# Generated by Django 4.1.4 on 2023-01-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=50, verbose_name="タイトル"),
        ),
    ]
