# Generated by Django 4.1.4 on 2022-12-20 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_uservideosettings_image_quality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservideosettings",
            options={"verbose_name_plural": "動画設定"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "ユーザー"},
        ),
        migrations.AlterField(
            model_name="uservideosettings",
            name="image_quality",
            field=models.CharField(
                choices=[("low", "低画質"), ("standard", "標準"), ("high", "高画質")],
                default="standard",
                max_length=20,
                verbose_name="画質",
            ),
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=500, verbose_name="コメント")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name=""),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.video"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "フィードバックコメント",
            },
        ),
    ]
