# Generated by Django 4.1.4 on 2023-01-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_video_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, null=True, verbose_name="ユーザ名"),
        ),
    ]
