# Generated by Django 4.1.4 on 2023-01-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=models.EmailField(max_length=254, verbose_name="メールアドレス"),
                max_length=50,
                unique=True,
                verbose_name="ユーザ名",
            ),
        ),
    ]
