# Generated by Django 4.1.4 on 2023-01-20 03:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                upload_to=main.models.video_directory_path, verbose_name="ビデオファイル"
            ),
        ),
        migrations.DeleteModel(
            name="UserVideoSettings",
        ),
    ]
