# Generated by Django 4.1.4 on 2023-01-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_user_is_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="ゲスト", max_length=50, verbose_name="ユーザ名"),
        ),
    ]
