# Generated by Django 4.1.4 on 2023-01-26 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
