# Generated by Django 4.1.4 on 2023-02-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_video_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoComment",
        ),
    ]
