# Generated by Django 4.1.4 on 2023-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_authenticationcode_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="uploaded_date",
            new_name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=50, verbose_name="タイトル"),
        ),
    ]
