# Generated by Django 4.1.4 on 2023-02-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_rename_uploaded_date_video_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.TextField(max_length=500, verbose_name="プロフィール"),
        ),
    ]
