# Generated by Django 4.1.4 on 2023-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="authenticationcode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
